### ISSUE TITLE
how to run this repo

### ISSUE THREAD

**Issue by Light--** [fangzong12/Multi-task_face_attribute#1]
Excuse me, may i ask how to run (train/validate/test) this repo？ Where to put the dataset and where is the pre-trained model ?

I have run this repo, but no matter which script i run, all caused error:

train: 
```
$ python trainRNet.py
Traceback (most recent call last):
  File "trainRNet.py", line 27, in <module>
    logDir = str(sys.argv[-2])
IndexError: list index out of range
```

test: 
```
$ python test_celebA.py
WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:11: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

(64, 24, 24, 3)
WARNING:tensorflow:From /home/user1/miniconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/RNet_models.py:11: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.

(64, 22, 22, 28)
(64, 11, 11, 28)
(64, 9, 9, 48)
(64, 4, 4, 48)
(64, 3, 3, 64)
WARNING:tensorflow:From /home/user1/miniconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
(64, 576)
(64, 128)
(64, 2)
(64, 2)
(64, 2)
(64, 2)
(64, 2)
(64, 2)
WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:17: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2020-06-04 10:19:37.543939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
2020-06-04 10:19:37.562138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:02:00.0
2020-06-04 10:19:37.564394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:03:00.0
2020-06-04 10:19:37.566612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:82:00.0
2020-06-04 10:19:37.568722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
pciBusID: 0000:83:00.0
2020-06-04 10:19:37.568904: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.569058: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.569205: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.569346: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.569486: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.569624: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
2020-06-04 10:19:37.574677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
2020-06-04 10:19:37.574714: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...
2020-06-04 10:19:37.575126: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-06-04 10:19:37.588491: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099955000 Hz
2020-06-04 10:19:37.590498: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55db4845aac0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-04 10:19:37.590527: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-06-04 10:19:38.132037: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55db484bd2b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2020-06-04 10:19:38.132086: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
2020-06-04 10:19:38.132098: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TITAN Xp, Compute Capability 6.1
2020-06-04 10:19:38.132108: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): TITAN Xp, Compute Capability 6.1
2020-06-04 10:19:38.132123: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): TITAN Xp, Compute Capability 6.1
2020-06-04 10:19:38.132555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2020-06-04 10:19:38.132579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:18: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

/nfs/data/DRG/fz/face_classfy_model/08011734/RNet0801-30
Traceback (most recent call last):
  File "test_celebA.py", line 30, in <module>
    RNet = Predict(R_Net, 24, batch_size[1], model_path[0])
  File "/home/user1/repo/Multi-task_face_attribute/face_cls/predict.py", line 24, in __init__
    assert  readstate, "the params dictionary is not valid"
AssertionError: the params dictionary is not valid
```

Thanks.

**Comment by fangzong12** [comment]
Sys. argv is the list of parameters you want to give to the training script. Of course, you can give logDir a specific path to the log.Since the trained model is not available, you will definitely not be able to run the test code

**Comment by fangzong12** [comment]
> Excuse me, may i ask how to run (train/validate/test) this repo？ Where to put the dataset and where is the pre-trained model ?
> 
> I have run this repo, but no matter which script i run, all caused error:
> 
> train:
> 
> ```
> $ python trainRNet.py
> Traceback (most recent call last):
>   File "trainRNet.py", line 27, in <module>
>     logDir = str(sys.argv[-2])
> IndexError: list index out of range
> ```
> 
> test:
> 
> ```
> $ python test_celebA.py
> WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:11: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.
> 
> (64, 24, 24, 3)
> WARNING:tensorflow:From /home/user1/miniconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1057: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
> Instructions for updating:
> Please use `layer.__call__` method instead.
> WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/RNet_models.py:11: The name tf.get_variable is deprecated. Please use tf.compat.v1.get_variable instead.
> 
> (64, 22, 22, 28)
> (64, 11, 11, 28)
> (64, 9, 9, 48)
> (64, 4, 4, 48)
> (64, 3, 3, 64)
> WARNING:tensorflow:From /home/user1/miniconda3/lib/python3.7/site-packages/tensorflow_core/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
> Instructions for updating:
> Use keras.layers.flatten instead.
> (64, 576)
> (64, 128)
> (64, 2)
> (64, 2)
> (64, 2)
> (64, 2)
> (64, 2)
> (64, 2)
> WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:17: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.
> 
> 2020-06-04 10:19:37.543939: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1
> 2020-06-04 10:19:37.562138: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
> name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:02:00.0
> 2020-06-04 10:19:37.564394: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 1 with properties:
> name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:03:00.0
> 2020-06-04 10:19:37.566612: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 2 with properties:
> name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:82:00.0
> 2020-06-04 10:19:37.568722: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 3 with properties:
> name: TITAN Xp major: 6 minor: 1 memoryClockRate(GHz): 1.582
> pciBusID: 0000:83:00.0
> 2020-06-04 10:19:37.568904: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcudart.so.10.0'; dlerror: libcudart.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.569058: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcublas.so.10.0'; dlerror: libcublas.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.569205: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcufft.so.10.0'; dlerror: libcufft.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.569346: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcurand.so.10.0'; dlerror: libcurand.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.569486: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusolver.so.10.0'; dlerror: libcusolver.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.569624: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcusparse.so.10.0'; dlerror: libcusparse.so.10.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /lib/x86_64-linux-gnu:/usr/lib/x86_64-linux-gnu::/usr/local/cuda-9.0/lib64:/opt/opencv-3/lib
> 2020-06-04 10:19:37.574677: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudnn.so.7
> 2020-06-04 10:19:37.574714: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1641] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> 2020-06-04 10:19:37.575126: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2020-06-04 10:19:37.588491: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2099955000 Hz
> 2020-06-04 10:19:37.590498: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55db4845aac0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
> 2020-06-04 10:19:37.590527: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
> 2020-06-04 10:19:38.132037: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55db484bd2b0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
> 2020-06-04 10:19:38.132086: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): TITAN Xp, Compute Capability 6.1
> 2020-06-04 10:19:38.132098: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (1): TITAN Xp, Compute Capability 6.1
> 2020-06-04 10:19:38.132108: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (2): TITAN Xp, Compute Capability 6.1
> 2020-06-04 10:19:38.132123: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (3): TITAN Xp, Compute Capability 6.1
> 2020-06-04 10:19:38.132555: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2020-06-04 10:19:38.132579: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]
> WARNING:tensorflow:From /home/user1/repo/Multi-task_face_attribute/face_cls/predict.py:18: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.
> 
> /nfs/data/DRG/fz/face_classfy_model/08011734/RNet0801-30
> Traceback (most recent call last):
>   File "test_celebA.py", line 30, in <module>
>     RNet = Predict(R_Net, 24, batch_size[1], model_path[0])
>   File "/home/user1/repo/Multi-task_face_attribute/face_cls/predict.py", line 24, in __init__
>     assert  readstate, "the params dictionary is not valid"
> AssertionError: the params dictionary is not valid
> ```
> 
> Thanks.

Sys. argv is the list of parameters you want to give to the training script. Of course, you can give logDir a specific path to the log.Since the trained model is not available, you will definitely not be able to run the test code

**Comment by Light--** [comment]
> Since the trained model is not available, you will definitely not be able to run the test code

Thans for your reply! Could you please share the trained model so we can run and test the code? Thank you.
